# Generated by Django 4.1.5 on 2023-08-18 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0002_facturaenc_facturadet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturadet',
            options={'permissions': [('del_facturadet', 'permisos de admin de caja')], 'verbose_name': 'Detalle Factura', 'verbose_name_plural': 'Detalles Facturas'},
        ),
        migrations.AlterModelOptions(
            name='facturaenc',
            options={'permissions': [('del_facturaenc', 'permisos de admin de caja')], 'verbose_name': 'Encabezado Factura', 'verbose_name_plural': 'Encabezado Facturas'},
        ),
    ]
