# Generated by Django 4.1.5 on 2023-09-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0004_cliente_direccion_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
