# Generated by Django 4.1.5 on 2023-10-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0005_cliente_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaenc',
            name='direccion_factura',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='nit_factura',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='nombre_factura',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='numero_factura',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='numero_interno',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='serie_factura',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
