# Generated by Django 4.1.5 on 2023-10-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fac", "0006_facturaenc_direccion_factura_facturaenc_nit_factura_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facturaenc",
            name="numero_autorizacion",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="facturaenc",
            name="numero_factura",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="facturaenc",
            name="numero_interno",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="facturaenc",
            name="serie_factura",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
