# Generated by Django 4.1.5 on 2023-10-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fac", "0007_facturaenc_numero_autorizacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facturaenc",
            name="estado_fel",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
