# Generated by Django 4.1.5 on 2023-10-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fac", "0009_alter_facturadet_cantidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facturadet",
            name="cantidad",
            field=models.BigIntegerField(default=0),
        ),
    ]
